// Database type definitions
// This file will be auto-generated by Supabase CLI or manually typed based on schema

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export type UserType = 'customer' | 'restaurant' | 'driver' | 'admin';
export type RestaurantStatus = 'pending_verification' | 'verified' | 'rejected' | 'suspended';
export type DriverStatus = 'pending_verification' | 'verified' | 'rejected' | 'suspended';
export type DocumentType = 'id_card' | 'passport' | 'drivers_license';
export type OrderStatus =
    | 'pending_payment'
    | 'paid'
    | 'confirmed'
    | 'preparing'
    | 'ready_for_pickup'
    | 'picked_up'
    | 'delivering'
    | 'delivered'
    | 'cancelled';
export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'refunded';
export type RecipientType = 'restaurant' | 'driver';
export type PayoutStatus = 'pending' | 'processing' | 'completed' | 'failed';

export interface Database {
    public: {
        Tables: {
            profiles: {
                Row: {
                    id: string;
                    user_type: UserType;
                    full_name: string;
                    phone: string | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id: string;
                    user_type: UserType;
                    full_name: string;
                    phone?: string | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    user_type?: UserType;
                    full_name?: string;
                    phone?: string | null;
                    updated_at?: string;
                };
            };
            restaurants: {
                Row: {
                    id: string;
                    user_id: string;
                    business_name: string;
                    nip: string;
                    address: string;
                    contact_person: string | null;
                    iban: string;
                    base_commission: number;
                    is_high_volume: boolean;
                    high_volume_commission: number;
                    status: RestaurantStatus;
                    latitude: number | null;
                    longitude: number | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    business_name: string;
                    nip: string;
                    address: string;
                    contact_person?: string | null;
                    iban: string;
                    base_commission?: number;
                    is_high_volume?: boolean;
                    high_volume_commission?: number;
                    status?: RestaurantStatus;
                    latitude?: number | null;
                    longitude?: number | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    business_name?: string;
                    nip?: string;
                    address?: string;
                    contact_person?: string | null;
                    iban?: string;
                    base_commission?: number;
                    is_high_volume?: boolean;
                    high_volume_commission?: number;
                    status?: RestaurantStatus;
                    latitude?: number | null;
                    longitude?: number | null;
                    updated_at?: string;
                };
            };
            drivers: {
                Row: {
                    id: string;
                    user_id: string;
                    pesel: string;
                    vehicle_type: string | null;
                    vehicle_plate: string | null;
                    iban: string;
                    status: DriverStatus;
                    is_available: boolean;
                    current_lat: number | null;
                    current_lng: number | null;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    user_id: string;
                    pesel: string;
                    vehicle_type?: string | null;
                    vehicle_plate?: string | null;
                    iban: string;
                    status?: DriverStatus;
                    is_available?: boolean;
                    current_lat?: number | null;
                    current_lng?: number | null;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    pesel?: string;
                    vehicle_type?: string | null;
                    vehicle_plate?: string | null;
                    iban?: string;
                    status?: DriverStatus;
                    is_available?: boolean;
                    current_lat?: number | null;
                    current_lng?: number | null;
                    updated_at?: string;
                };
            };
            driver_documents: {
                Row: {
                    id: string;
                    driver_id: string;
                    document_type: DocumentType;
                    file_url: string;
                    uploaded_at: string;
                };
                Insert: {
                    id?: string;
                    driver_id: string;
                    document_type: DocumentType;
                    file_url: string;
                    uploaded_at?: string;
                };
                Update: {
                    document_type?: DocumentType;
                    file_url?: string;
                };
            };
            restaurant_categories: {
                Row: {
                    id: string;
                    restaurant_id: string;
                    name: string;
                    display_order: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    restaurant_id: string;
                    name: string;
                    display_order?: number;
                    created_at?: string;
                };
                Update: {
                    name?: string;
                    display_order?: number;
                };
            };
            menu_items: {
                Row: {
                    id: string;
                    restaurant_id: string;
                    category_id: string | null;
                    name: string;
                    description: string | null;
                    price: number;
                    image_url: string | null;
                    is_available: boolean;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    restaurant_id: string;
                    category_id?: string | null;
                    name: string;
                    description?: string | null;
                    price: number;
                    image_url?: string | null;
                    is_available?: boolean;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    category_id?: string | null;
                    name?: string;
                    description?: string | null;
                    price?: number;
                    image_url?: string | null;
                    is_available?: boolean;
                    updated_at?: string;
                };
            };
            orders: {
                Row: {
                    id: string;
                    order_number: string;
                    customer_id: string;
                    restaurant_id: string;
                    driver_id: string | null;
                    subtotal: number;
                    delivery_fee: number;
                    total_amount: number;
                    platform_commission: number;
                    delivery_address: string;
                    delivery_lat: number | null;
                    delivery_lng: number | null;
                    distance_km: number | null;
                    status: OrderStatus;
                    p24_transaction_id: string | null;
                    payment_status: PaymentStatus;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    order_number?: string;
                    customer_id: string;
                    restaurant_id: string;
                    driver_id?: string | null;
                    subtotal: number;
                    delivery_fee: number;
                    total_amount: number;
                    platform_commission: number;
                    delivery_address: string;
                    delivery_lat?: number | null;
                    delivery_lng?: number | null;
                    distance_km?: number | null;
                    status?: OrderStatus;
                    p24_transaction_id?: string | null;
                    payment_status?: PaymentStatus;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    driver_id?: string | null;
                    status?: OrderStatus;
                    p24_transaction_id?: string | null;
                    payment_status?: PaymentStatus;
                    updated_at?: string;
                };
            };
            order_items: {
                Row: {
                    id: string;
                    order_id: string;
                    menu_item_id: string | null;
                    quantity: number;
                    price_at_order: number;
                    item_name: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    order_id: string;
                    menu_item_id?: string | null;
                    quantity: number;
                    price_at_order: number;
                    item_name: string;
                    created_at?: string;
                };
                Update: {
                    quantity?: number;
                };
            };
            payouts: {
                Row: {
                    id: string;
                    order_id: string;
                    recipient_type: RecipientType;
                    recipient_id: string;
                    amount: number;
                    iban: string;
                    status: PayoutStatus;
                    p24_payout_id: string | null;
                    error_message: string | null;
                    processed_at: string | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    order_id: string;
                    recipient_type: RecipientType;
                    recipient_id: string;
                    amount: number;
                    iban: string;
                    status?: PayoutStatus;
                    p24_payout_id?: string | null;
                    error_message?: string | null;
                    processed_at?: string | null;
                    created_at?: string;
                };
                Update: {
                    status?: PayoutStatus;
                    p24_payout_id?: string | null;
                    error_message?: string | null;
                    processed_at?: string | null;
                };
            };
        };
        Functions: {
            calculate_delivery_fee: {
                Args: { distance_km: number };
                Returns: number;
            };
            calculate_commission: {
                Args: { rest_id: string };
                Returns: number;
            };
            generate_order_number: {
                Args: Record<string, never>;
                Returns: string;
            };
        };
    };
}
